---
title: "Wasted Money: Toronto Police Budget and Crime Number"
subtitle: "Analyzing the changes in annual police budget and its effects
on the number of crimes within Toronto"
author: 
  - Yisu Hou
thanks: "Code and data supporting this analysis are available at: 
https://github.com/YisuHou1/Toronto-Police-Budget-Statistics."
date: today
date-format: long
abstract: "An analysis of Toronto's annual police budget and crime counts
was conducted to determine the effectiveness of the budget in preventing
crime within the city."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(knitr)
library(kableExtra)

data_bud <- read_csv(here::here("data/analysis_data/analysis_budget_data.csv"))
data_cri <- read_csv(here::here("data/analysis_data/analysis_crime_data.csv"))

```


# Introduction




# Data {#sec-mydatasection}



```{r}


```

Talk more about it.


\newpage

\appendix

# Appendix {-}




\newpage


# References
@r
@tidyverse
@dplyr
@knitr
@kextra
@opendatatoronto

